/**
 * 此文件由 Meoo Cloud 自动生成，请勿手动修改！
 * This file is auto-generated by Meoo Cloud. Do not edit manually!
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export function getSupabaseUrl(): string {
  return `${(window as any).MEOO_CONFIG?.meoo_app_access_url || window.location.origin}/sb-api`;
}

export const supabaseUrl = getSupabaseUrl();
export const supabaseAnonKey = import.meta.env.DEV ? (import.meta.env.MEOO_LOCAL_ANON_KEY || '') : 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzg0NzM3MzYxLCJleHAiOjEzMjk1Mzc3MzYxfQ.65T2nQ5yEkZNKxCz8PKuOPouy8Gmoib2_efhy6GV4X8';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
